### ISSUE TITLE
Compilation Unit is not on the build path of a Java Project

### ISSUE THREAD

**Issue by pdhruv93** [smclab/liferay-7-workspace#3]
When I import the Liferay workspace in Liferay IDE it gives me error:
![image](https://user-images.githubusercontent.com/38987871/58759049-ca43b180-852c-11e9-9c6a-83e4d9e235e6.png)

**Comment by mmariuzzo** [comment]
Hi, I have upgraded the workspace scripts to allows import. Please try again

**Comment by yuchi** [comment]
@pdhruv93 Did the changes solve your problem?

In case you are having problems upgrading, just

1. `git pull` from the cloned repository
2. Remove the project from Eclipse
3. Re-import the project into Eclipse
4. It should work now :)

I’m gonna close the issue. Please re-open if you find any new problem.
Thanks for reporting it!
